server:
  port: 5489

spring:
  application:
    name: train-service
  datasource:
    url: jdbc:mysql://localhost:3309/SCH?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: 'update'
  main:
    allow-circular-references: true
  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


springdoc:
  api-docs:
    groups:
      enabled: true
    path: /train-service/v3/api-docs
  swagger-ui:
    enabled: false