server:
  port: 6485

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/ticket-service
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: 'update'
  main:
    allow-circular-references: true
  output:
    ansi:
      enabled: ALWAYS



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


springdoc:
  api-docs:
    groups:
      enabled: true
    path: /ticket-service/v3/api-docs
  swagger-ui:
    enabled: false


